# Generated by Django 5.0.6 on 2024-10-06 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AJKapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregister',
            name='bio',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='userregister',
            name='profilepic',
            field=models.ImageField(default='', upload_to='images'),
        ),
    ]
