# Generated by Django 5.0.6 on 2024-10-07 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AJKapp', '0002_userregister_bio_userregister_profilepic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregister',
            name='bio',
            field=models.TextField(default='Add Something About Yourself...'),
        ),
        migrations.AlterField(
            model_name='userregister',
            name='profilepic',
            field=models.ImageField(default='{%static "signupbg.jpg" %}', upload_to='images'),
        ),
    ]
