# Generated by Django 5.0.6 on 2024-10-15 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AJKapp', '0004_alter_userregister_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregister',
            name='profilepic',
            field=models.ImageField(default='{%static "signupbg.jpg" %}', upload_to='images/'),
        ),
    ]
