# Generated by Django 5.0.6 on 2024-10-15 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AJKapp', '0005_alter_userregister_profilepic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregister',
            name='profilepic',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
